/**********************************************************************************************************************
 * \file GPT12_Timer_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GPT12_Timer_Interrupt.h"
#include "Ifx_Types.h"
#include "IfxGpt12.h"
#include "IfxPort.h"
#include "Bsp.h"
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "I2C_Read_Ext_Device.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <Driver_Can1.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_GPT12_TIMER_T2  10                       /* Define the GPT12 Timer interrupt priority            */
#define ISR_PROVIDER_GPT12_TIMER     IfxSrc_Tos_cpu0         /* Interrupt provider                                   */
#define RELOAD_VALUE                 48828u                  /* Reload value to have an interrupt each 500ms         */
#define RELOAD_VALUE_200ms           19531u
#define RELOAD_VALUE_50ms            4883u
#define RELOAD_VALUE_10ms            977u

#define Velocity_Mode           1
#define Position_Mode           2

#define WAIT_TIME                    1
/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/

/* Macro defining the Interrupt Service Routine */
IFX_INTERRUPT(interruptGpt12_T2, 0, ISR_PRIORITY_GPT12_TIMER_T2);
/* Function to initialize the GPT12 and start the timer */
union
{
    uint16 data;
    uint8 a[2];
} output;

//extern int flag;
extern int Mode_Select;
uint16 Output_Data ;

void initGpt12Timer(void)
{
    /* Initialize the GPT12 module */
    IfxGpt12_enableModule(&MODULE_GPT120); /* Enable the GPT12 module */
    IfxGpt12_setGpt1BlockPrescaler(&MODULE_GPT120, IfxGpt12_Gpt1BlockPrescaler_16); /* Set GPT1 block prescaler */

    /* Initialize the Timer T2 */
    IfxGpt12_T2_setMode(&MODULE_GPT120, IfxGpt12_Mode_timer);                           /* Set T2 to reload mode */
    IfxGpt12_T2_setTimerValue(&MODULE_GPT120, RELOAD_VALUE_200ms);                      /* Set T2 reload value */

    /* Initialize the interrupt */
    volatile Ifx_SRC_SRCR *src_t2 = IfxGpt12_T2_getSrc(&MODULE_GPT120);                 /* Get the interrupt address  */
    IfxSrc_init(src_t2, ISR_PROVIDER_GPT12_TIMER, ISR_PRIORITY_GPT12_TIMER_T2);         /* Initialize service request */
    IfxSrc_enable(src_t2);                                                              /* Enable GPT12 interrupt  */

    IfxGpt12_T2_run(&MODULE_GPT120, IfxGpt12_TimerRun_start);                           /* Start the timer  */
}

/* Interrupt Service Routine of the GPT12 */
void interruptGpt12_T2(void)
{
    READ_EXT_DEVICE_ADDRESS();

    Output_Data = RX_BUFF();

    output.data = Output_Data;
    if(Mode_Select == Velocity_Mode)
    {
    MOTOR_MODE_VEL();
    CAN_TEST_VEL(output.a[0],output.a[1]);
    }
    else if(Mode_Select == Position_Mode)
    {
    MOTOR_MODE_POS();
    CAN_TEST_POS(output.a[0],output.a[1]);
    }

}

